[package]
name = "du-dust"
description = "A more intuitive version of du"
version = "0.4.0"
authors = ["bootandy <bootandy@gmail.com>", "nebkor <code@ardent.nebcorp.com>"]
edition = "2018"

documentation = "https://github.com/bootandy/dust"
homepage = "https://github.com/bootandy/dust"
repository = "https://github.com/bootandy/dust"

keywords = ["du", "command-line", "disk", "disk-usage"]
categories = ["command-line-utilities"]
license = "Apache-2.0"

[badges]
travis-ci = {repository = "https://travis-ci.org/bootandy/dust"}

[[bin]]
name = "dust"
path = "src/main.rs"

[dependencies]
ansi_term = "=0.11"
assert_cli = "=0.5"
clap = "=2.33"
ignore = "=0.4"
tempfile = "=3"
walkdir = "=2"
